### ISSUE TITLE
Folders are always at the top

### ISSUE THREAD

**Issue by OnurGumus** [farlee2121/ionide-and-vscode-solution-explorer#1]
I have observed, while file order works perfectly fine, if you have your files in folders then they appear to be at the top of the project.

**Comment by farlee2121** [comment]
The [vscode-solution-explorer](https://github.com/fernandoescolar/vscode-solution-explorer) is still the place to post this issue.
If I accepted Ionide or vscode-solution-explorer issues here, I'd have to repeat them in the source project to get feedback anyway.

**Comment by OnurGumus** [comment]
Alright
